
version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  # HTTP Proxy for identifying sessions
  # https://github.com/mu-semtech/mu-identifier
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
    links:
      - dispatcher:dispatcher
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"

  # Reverse proxy that configures endpoints
  # https://github.com/mu-semtech/mu-dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"

  # Front-end made for BNB
  # https://github.com/lblod/frontend-burgernabije-besluitendatabank
  frontend:
    # image: lennybontenakel/frontend-validation:latest
    image: snenenenene/frontend-validation-tool:latest
    env_file:
      - path: ./default.env
    links:
      - identifier
      - cors-container
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"

  # CORS Anywhere service
  cors-container:
    image: cors-container
    restart: always
    ports:
      - "3000:3000"

    logging: *default-logging
    labels:
      - "logging=true"
